### These are arithmetic operations with size sized arrays. Operations between differently sized arrays is called broadcasting

In [1]:
import numpy as np

In [2]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])

In [3]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [4]:
arr * arr # Multiplication

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [5]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [7]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [8]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])

In [9]:
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [10]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])