In [1]:
import numpy as np

In [2]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [3]:
data = np.random.randn(7, 4)

In [4]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [5]:
data

array([[-1.09599551e+00,  1.14290575e+00,  1.21721249e-01,
         6.04072508e-02],
       [ 1.36091830e-02, -1.65076627e+00, -1.24704037e+00,
        -9.61113358e-01],
       [-2.12822024e-01,  1.91416003e-01,  7.80468295e-01,
         9.04330531e-01],
       [-1.18692544e+00,  3.13866202e-01, -8.07550912e-01,
         1.74038910e+00],
       [-1.56324824e-01,  7.27990815e-01,  1.70597528e-03,
         6.84843946e-01],
       [-5.00394608e-01,  4.51322081e-01,  1.52165463e+00,
        -3.35455329e-01],
       [ 1.25392598e+00,  4.29790646e-01,  2.93297255e-01,
        -7.79644847e-01]])

#### Suppose each name corresponds to a row in the data array and we wanted to select all the rows with corresponding name 'Bob'.

In [8]:
print(len(names))
print(len(data))

7
7


In [6]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [7]:
data[names == 'Bob']

array([[-1.09599551,  1.14290575,  0.12172125,  0.06040725],
       [-1.18692544,  0.3138662 , -0.80755091,  1.7403891 ]])

In [9]:
data[names == 'Bob' , 2:]

array([[ 0.12172125,  0.06040725],
       [-0.80755091,  1.7403891 ]])

In [10]:
data[names == 'Bob' , 3]

array([0.06040725, 1.7403891 ])

In [11]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [12]:
data[~(names == 'Bob')]

array([[ 0.01360918, -1.65076627, -1.24704037, -0.96111336],
       [-0.21282202,  0.191416  ,  0.78046829,  0.90433053],
       [-0.15632482,  0.72799081,  0.00170598,  0.68484395],
       [-0.50039461,  0.45132208,  1.52165463, -0.33545533],
       [ 1.25392598,  0.42979065,  0.29329725, -0.77964485]])

In [13]:
cond = names == 'Bob'

In [14]:
data[~cond]

array([[ 0.01360918, -1.65076627, -1.24704037, -0.96111336],
       [-0.21282202,  0.191416  ,  0.78046829,  0.90433053],
       [-0.15632482,  0.72799081,  0.00170598,  0.68484395],
       [-0.50039461,  0.45132208,  1.52165463, -0.33545533],
       [ 1.25392598,  0.42979065,  0.29329725, -0.77964485]])

In [15]:
mask = (names == 'Bob') | (names == 'Will')

In [16]:
mask

array([ True, False,  True,  True,  True, False, False])

In [17]:
data[mask]

array([[-1.09599551e+00,  1.14290575e+00,  1.21721249e-01,
         6.04072508e-02],
       [-2.12822024e-01,  1.91416003e-01,  7.80468295e-01,
         9.04330531e-01],
       [-1.18692544e+00,  3.13866202e-01, -8.07550912e-01,
         1.74038910e+00],
       [-1.56324824e-01,  7.27990815e-01,  1.70597528e-03,
         6.84843946e-01]])

In [18]:
data

array([[-1.09599551e+00,  1.14290575e+00,  1.21721249e-01,
         6.04072508e-02],
       [ 1.36091830e-02, -1.65076627e+00, -1.24704037e+00,
        -9.61113358e-01],
       [-2.12822024e-01,  1.91416003e-01,  7.80468295e-01,
         9.04330531e-01],
       [-1.18692544e+00,  3.13866202e-01, -8.07550912e-01,
         1.74038910e+00],
       [-1.56324824e-01,  7.27990815e-01,  1.70597528e-03,
         6.84843946e-01],
       [-5.00394608e-01,  4.51322081e-01,  1.52165463e+00,
        -3.35455329e-01],
       [ 1.25392598e+00,  4.29790646e-01,  2.93297255e-01,
        -7.79644847e-01]])

In [20]:
data

array([[-1.09599551e+00,  1.14290575e+00,  1.21721249e-01,
         6.04072508e-02],
       [ 1.36091830e-02, -1.65076627e+00, -1.24704037e+00,
        -9.61113358e-01],
       [-2.12822024e-01,  1.91416003e-01,  7.80468295e-01,
         9.04330531e-01],
       [-1.18692544e+00,  3.13866202e-01, -8.07550912e-01,
         1.74038910e+00],
       [-1.56324824e-01,  7.27990815e-01,  1.70597528e-03,
         6.84843946e-01],
       [-5.00394608e-01,  4.51322081e-01,  1.52165463e+00,
        -3.35455329e-01],
       [ 1.25392598e+00,  4.29790646e-01,  2.93297255e-01,
        -7.79644847e-01]])

#### Selecting data from an array by boolean indexing always creates a copy of the data, even if the returned array is unchanged.

In [21]:
data[data < 0] = 0

In [22]:
data

array([[0.00000000e+00, 1.14290575e+00, 1.21721249e-01, 6.04072508e-02],
       [1.36091830e-02, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 1.91416003e-01, 7.80468295e-01, 9.04330531e-01],
       [0.00000000e+00, 3.13866202e-01, 0.00000000e+00, 1.74038910e+00],
       [0.00000000e+00, 7.27990815e-01, 1.70597528e-03, 6.84843946e-01],
       [0.00000000e+00, 4.51322081e-01, 1.52165463e+00, 0.00000000e+00],
       [1.25392598e+00, 4.29790646e-01, 2.93297255e-01, 0.00000000e+00]])

In [23]:
data[names != 'Joe'] = 7

In [24]:
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.01360918, 0.        , 0.        , 0.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.45132208, 1.52165463, 0.        ],
       [1.25392598, 0.42979065, 0.29329725, 0.        ]])