In [1]:
import numpy as np

In [2]:
data1 =  [6, 7.5, 8, 0, 1]

In [3]:
arr1 = np.array(data1)

In [4]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [5]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

In [6]:
arr2 = np.array(data2)

In [7]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [8]:
arr2.ndim # for dimension

2

In [9]:
arr2.shape # 2 rows 4 columns

(2, 4)

In [10]:
arr1.dtype

dtype('float64')

In [11]:
arr2.dtype

dtype('int64')

In [12]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

##### Higher Dimension Array

In [13]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [21]:
np.empty((2,3,2))

array([[[9.45410424e-312, 3.16202013e-322],
        [0.00000000e+000, 0.00000000e+000],
        [1.07444599e-296, 9.85122374e+165]],

       [[1.33974594e-075, 5.55525329e+170],
        [2.23078868e+160, 2.67784836e+184],
        [1.80135427e+185, 2.33743897e-052]]])

#### It’s not safe to assume that np.empty will return an array of all zeros. In some cases, it may return uninitialized “garbage” values.

In [22]:
np.arange(15) # same as python's range() function

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])