#### Fancy indexing is a term adopted by NumPy to describe indexing using integer arrays.

In [1]:
import numpy as np

In [2]:
arr = np.empty((8,4))

In [3]:
arr

array([[ 6.01347002e-154,  2.64519872e+185,  1.94855594e+227,
         3.81996749e+180],
       [ 1.21906099e-152,  3.11080962e+161,  2.52301625e-258,
         6.01347002e-154],
       [ 1.59704334e+241,  4.04452398e-311,  3.65549792e+098,
         2.00461979e-313],
       [ 1.54511808e-253,  1.17205752e+171,  4.12661543e-313,
         1.16518789e-310],
       [ 1.78615730e-202,  5.88354855e+224,  6.65485141e-244,
         2.65648749e-309],
       [-5.98008223e+197,  4.84027240e-311,  4.49006859e-319,
         6.95335581e-309],
       [ 3.55067379e+197,  2.02083155e-309,  1.94906280e+289,
         5.40073039e-319],
       [ 7.32788743e-314, -1.55291134e-101, -4.77830973e-299,
         9.36663773e-314]])

In [4]:
for i in range(8):
    arr[i] = i

In [5]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

#### To select out a subset of the rows in a particular order, you can simply pass a list or ndarray of integers specifying the desired order

In [6]:
arr[[4,3,0,6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

#### Using negative indices selects rows from the end

In [7]:
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

#### Passing multiple index arrays does something slightly different , it selects a one-dimensional array of elements corresponding to each tuple of indices.

In [8]:
arr = np.arange(32).reshape((8, 4))

In [9]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [10]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

#### The behavior of fancy indexing in this case is a bit different from what some users might have expected (myself included), which is the rectangular region formed by selecting a subset of the matrix’s rows and columns

In [11]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])