In [1]:
import numpy as np

In [2]:
arr = np.arange(10)

In [3]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr[5]

np.int64(5)

In [5]:
arr[5:8]

array([5, 6, 7])

In [6]:
arr[5:8] = 12 

In [7]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

#### array slices are views on the original array

In [8]:
arr_slice = arr[5:8]

In [9]:
arr_slice

array([12, 12, 12])

#### Now, when I change values in arr_slice, the mutations are reflected in the original array arr:

In [10]:
arr_slice[1] = 12345

In [11]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

#### The “bare” slice [:] will assign to all values in an array:

In [12]:
arr_slice[:] = 64

In [13]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

#### If you want a copy of a slice of an ndarray instead of a view, you will need to explicitly copy the array—for example, arr[5:8].copy().

In [14]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [15]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
arr2d[2]

array([7, 8, 9])

In [17]:
arr2d[0][2]

np.int64(3)

In [18]:
arr2d[0, 2]

np.int64(3)

#### In multidimensional arrays, if you omit later indices, the returned object will be a lower dimensional ndarray consisting of all the data along the higher dimensions.

In [19]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [21]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [20]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
old_values = arr3d[0].copy()

In [23]:
arr3d[0] = 42

In [24]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [25]:
arr3d[0] = old_values

In [26]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [27]:
arr3d[1,0]

array([7, 8, 9])

In [28]:
x = arr3d[1]

In [29]:
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [30]:
x[0]

array([7, 8, 9])

In [31]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [32]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [33]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

#### arr2d[:2] means “select the first two rows of arr2d.”

In [36]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

#### To select the second row but only the first two columns 

In [37]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
arr2d[1,:2]

array([4, 5])

#### To select the third column but only the first two rows 

In [40]:
arr2d[:2,2]

array([3, 6])

#### Assigning to a slice expression asigns to the whole selection

In [42]:
arr2d[:2,1:] = 0

In [43]:
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

In [44]:
first_arr = arr2d[2]
second_arr = arr2d[2,:]
third_arr = arr2d[2:,:]

In [46]:
print(f"first arr : {first_arr}")
print(f"shape fo first arr : {first_arr.shape}")

print(f"second arr : {second_arr}")
print(f"shape fo second arr : {second_arr.shape}")

print(f"third arr : {third_arr}")
print(f"shape fo third arr : {third_arr.shape}")

first arr : [7 8 9]
shape fo first arr : (3,)
second arr : [7 8 9]
shape fo second arr : (3,)
third arr : [[7 8 9]]
shape fo third arr : (1, 3)
