In [1]:
import numpy as np

In [2]:
arr = np.arange(15).reshape((3,5))

In [3]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [4]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [5]:
arr = np.random.randn(6,3)

In [6]:
arr

array([[-0.73777599,  0.13761706, -0.05816329],
       [-0.78937669,  0.34593128, -0.99040598],
       [ 0.96108593,  0.45955024,  0.15359222],
       [-0.67703342,  0.41511872, -1.55250042],
       [ 0.22323362,  1.65310604, -1.66074861],
       [-0.68306738, -0.54357613,  0.15336662]])

In [7]:
np.dot(arr.T,arr)

array([[ 3.06590369,  0.52634534,  1.54793021],
       [ 0.52634534,  3.55035145, -3.7532653 ],
       [ 1.54793021, -3.7532653 ,  6.19974237]])

In [8]:
arr = np.arange(16).reshape((2, 2, 4))

In [9]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [10]:
arr.transpose((1,0,2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

#### the axes have been reordered with the second axis first, the first axis second, and the last axis unchanged

In [11]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [12]:
arr.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])