## Calling astype always creates a new array (a copy of the data), even if the new dtype is the same as the old dtype.

In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5])

In [3]:
arr.dtype

dtype('int64')

In [4]:
float_arr = arr.astype(np.float64)

In [5]:
float_arr.dtype

dtype('float64')

In [6]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])

In [7]:
arr.dtype

dtype('float64')

In [8]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [14]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.bytes_)

In [15]:
numeric_strings.dtype

dtype('S4')

In [16]:
numeric_strings.astype(np.float64)

array([ 1.25, -9.6 , 42.  ])

##### It’s important to be cautious when using the numpy.bytes_ type, as string data in NumPy is fixed size and may truncate input without warning.

In [17]:
int_arr = np.arange(10)

In [18]:
calibers = np.array([.22, .270, .357, .380, .44, .50] , dtype=np.float64)

In [19]:
int_arr.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

##### There are shorthand type code strings you can also use to refer to a dtype:

In [20]:
empty_uint32 = np.empty(8, dtype='u4')
empty_uint32

array([   4128860,    6029375,    3801155,    5570652,    6619251,
          7536754, 2459435008,        369], dtype=uint32)