In [2]:
import numpy as np

In [3]:
list_ = [ '1' , '2' , '3' , '4' ,'5' ]
array_list = np.array(object = list_)

In [8]:
# Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
# to print the data types of both the variables.

In [4]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [5]:
type(list_)

list

In [6]:
type(array_list)

numpy.ndarray

In [9]:
print("There is no change in the data type of the variables list but array_list datatype is numpy.ndarray")

There is no change in the data type of the variables list but array_list datatype is numpy.ndarray


In [10]:
# Q2. Write a code to print the data type of each and every element of both the variables list_ and
# array_list.

In [15]:
for i in array_list:
    print(type(i))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [17]:
for i in list_:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [18]:
# Q3. Considering the following changes in the variable, array_list:

In [19]:
array_list = np.array(object = list_, dtype = int)

In [20]:
array_list

array([1, 2, 3, 4, 5])

In [21]:
# Will there be any difference in the data type of the elements present in both the variables, list_ and
# arra_list? If so then print the data types of each and every element present in both the variables, list_
# and arra_list.

In [23]:
print(type(list_))

<class 'list'>


In [25]:
print(type(array_list))

<class 'numpy.ndarray'>


In [27]:
print("There will change in datatype of the elements present in array_list but there will no change in the datatype of the elements present in list_")

There will change in datatype of the elements present in array_list but there will no change in the datatype of the elements present in list_


In [28]:
for i in array_list:
    print(type(i))

<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [30]:
for i in list_:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [34]:
import numpy as np
num_list = [[ 1 , 2 , 3 ] , [ 4 , 5 , 6 ]]
num_array = np.array(object = num_list)

In [35]:
num_array 

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
# Q4. Write a code to find the following characteristics of variable, num_array:
# (i) shape
# (ii) size

In [37]:
num_array.shape # means 2 rows and 3 columns

(2, 3)

In [38]:
num_array.size # means 6 elements are present in num_array

6

In [39]:
# Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
# creation function.

In [40]:
zeros_arr = np.zeros((3,3))

In [41]:
zeros_arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [42]:
zeros_arr.shape

(3, 3)

In [43]:
zeros_arr.size

9

In [44]:
# Q6. Create an identity matrix of shape (5,5) using numpy functions?

In [46]:
identity_matrix = np.eye(5)

In [47]:
identity_matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])