In [1]:
import numpy as np

### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.


In [2]:
arr1 = np.random.randint(1,20,(5,5))

In [3]:
arr1

array([[19, 14,  9, 18,  4],
       [14,  5,  4, 18,  4],
       [ 2,  4,  7, 13, 11],
       [19, 12, 19, 12,  8],
       [ 8,  3,  6, 19,  5]], dtype=int32)

In [6]:
arr1[:,2] = 1 # selecting third column 

In [7]:
arr1

array([[19, 14,  1, 18,  4],
       [14,  5,  1, 18,  4],
       [ 2,  4,  1, 13, 11],
       [19, 12,  1, 12,  8],
       [ 8,  3,  1, 19,  5]], dtype=int32)

2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [11]:
arr2 = np.arange(start=1,stop=17)

In [12]:
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [21]:
arr2 = arr2.reshape(4,4)

In [25]:
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [27]:
np.fill_diagonal(arr2,0)

In [28]:
arr2

array([[ 0,  2,  3,  4],
       [ 5,  0,  7,  8],
       [ 9, 10,  0, 12],
       [13, 14, 15,  0]])

### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.

In [29]:
arr3 = np.arange(1,37).reshape(6,6)

In [30]:
arr3

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [33]:
arr3[2:5,1:4]

array([[14, 15, 16],
       [20, 21, 22],
       [26, 27, 28]])

2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [36]:
arr4 = np.random.rand(5,5)

In [37]:
arr4

array([[0.9580643 , 0.44676293, 0.62322677, 0.64171224, 0.60789751],
       [0.65209862, 0.18856457, 0.64194897, 0.73198171, 0.64661731],
       [0.65661038, 0.83413881, 0.89796172, 0.59104753, 0.16335507],
       [0.34834971, 0.98775422, 0.94896093, 0.75303961, 0.75256934],
       [0.33121513, 0.41426886, 0.67824035, 0.20539158, 0.49174213]])

In [57]:
print(arr4[0,:])
print(arr4[-1,:])
print(arr4[1:-1,0])
print(arr4[1:-1,-1])
border_elements = np.concatenate((arr4[0,:],arr4[-1,:],arr4[1:-1,0],arr4[1:-1,-1]))

[0.9580643  0.44676293 0.62322677 0.64171224 0.60789751]
[0.33121513 0.41426886 0.67824035 0.20539158 0.49174213]
[0.65209862 0.65661038 0.34834971]
[0.64661731 0.16335507 0.75256934]


In [58]:
border_elements

array([0.9580643 , 0.44676293, 0.62322677, 0.64171224, 0.60789751,
       0.33121513, 0.41426886, 0.67824035, 0.20539158, 0.49174213,
       0.65209862, 0.65661038, 0.34834971, 0.64661731, 0.16335507,
       0.75256934])

### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.

In [62]:
arr5 = np.random.randint(1,13,(3,4))

In [63]:
arr6 = np.random.randint(1,13,(3,4))

In [64]:
arr5

array([[ 8,  9,  2, 11],
       [ 2,  2,  1, 12],
       [ 8, 11,  6,  4]], dtype=int32)

In [65]:
arr6

array([[ 6,  6,  6,  5],
       [ 8,  4, 10,  1],
       [ 1,  4,  8,  5]], dtype=int32)

In [66]:
arr5+arr6

array([[14, 15,  8, 16],
       [10,  6, 11, 13],
       [ 9, 15, 14,  9]], dtype=int32)

In [67]:
arr5-arr6

array([[ 2,  3, -4,  6],
       [-6, -2, -9, 11],
       [ 7,  7, -2, -1]], dtype=int32)

In [68]:
arr5*arr6

array([[48, 54, 12, 55],
       [16,  8, 10, 12],
       [ 8, 44, 48, 20]], dtype=int32)

In [69]:
arr5/arr6

array([[ 1.33333333,  1.5       ,  0.33333333,  2.2       ],
       [ 0.25      ,  0.5       ,  0.1       , 12.        ],
       [ 8.        ,  2.75      ,  0.75      ,  0.8       ]])

2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [89]:
arr7 = np.arange(1,17).reshape(4,4)

In [91]:
arr7

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [92]:
# Compute the row-wise and column-wise sum
row_sum = np.sum(arr7, axis=1)
column_sum = np.sum(arr7, axis=0)

In [93]:
row_sum

array([10, 26, 42, 58])

In [94]:
column_sum

array([28, 32, 36, 40])

### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.

In [95]:
arr8 = np.random.randint(1,25,(5,5))

In [96]:
arr8

array([[14, 14, 11,  9,  2],
       [ 4, 17, 19,  8, 22],
       [11,  8, 15, 14,  2],
       [ 6,  5, 12, 14, 13],
       [15, 23, 14,  1, 18]], dtype=int32)

In [97]:
np.mean(arr8)

np.float64(11.64)

In [98]:
np.median(arr8)

np.float64(13.0)

In [99]:
np.std(arr8)

np.float64(5.932149694672244)

In [100]:
np.var(arr8)

np.float64(35.1904)

2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

In [102]:
arr9 = np.arange(1,10).reshape(3,3)

In [103]:
arr9

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [104]:
arr9.mean()

np.float64(5.0)

In [105]:
arr9.std()

np.float64(2.581988897471611)

In [109]:
normalized_arr = (arr9 - arr9.mean()) / arr9.std() 

In [110]:
normalized_arr

array([[-1.54919334, -1.161895  , -0.77459667],
       [-0.38729833,  0.        ,  0.38729833],
       [ 0.77459667,  1.161895  ,  1.54919334]])

In [111]:
normalized_arr.mean()

np.float64(0.0)

In [112]:
normalized_arr.std()

np.float64(1.0)

### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.

In [114]:
arr10 = np.random.randint(1,9,(3,3))

In [115]:
arr_1d = np.array([1,2,3])

In [116]:
arr10

array([[6, 3, 2],
       [7, 4, 6],
       [3, 8, 8]], dtype=int32)

In [117]:
arr_1d

array([1, 2, 3])

In [118]:
arr10 + arr_1d

array([[ 7,  5,  5],
       [ 8,  6,  9],
       [ 4, 10, 11]])

2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

In [119]:
arr11 = np.random.randint(1,17,(4,4))

In [128]:
arr_1d_1 = np.ones((4,))

In [129]:
arr11

array([[14, 11, 11,  1],
       [13, 10,  7,  4],
       [ 6,  5,  6,  8],
       [ 5,  6,  6,  3]], dtype=int32)

In [133]:
arr_1d_1 = arr_1d_1.reshape(4,1)

In [131]:
arr11

array([[14, 11, 11,  1],
       [13, 10,  7,  4],
       [ 6,  5,  6,  8],
       [ 5,  6,  6,  3]], dtype=int32)

In [134]:
arr_1d_1

array([[1.],
       [1.],
       [1.],
       [1.]])

In [135]:
arr11 - arr_1d_1

array([[13., 10., 10.,  0.],
       [12.,  9.,  6.,  3.],
       [ 5.,  4.,  5.,  7.],
       [ 4.,  5.,  5.,  2.]])

### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.

In [138]:
arr12 = np.random.randint(1,16,(3,3))

In [139]:
arr12

array([[ 8,  6, 13],
       [ 4, 11,  7],
       [ 2,  6,  6]], dtype=int32)

In [142]:
print("Determinant : ")
np.linalg.det(arr12)

Determinant : 


np.float64(157.9999999999999)

In [144]:
print("Inverse : ")
np.linalg.inv(arr12)

Inverse : 


array([[ 0.15189873,  0.26582278, -0.63924051],
       [-0.06329114,  0.13924051, -0.02531646],
       [ 0.01265823, -0.2278481 ,  0.40506329]])

In [145]:
print("Eigen values : ")
np.linalg.eigvals(arr12)

Eigen values : 


array([19.86238643+0.j        ,  2.56880678+1.16445939j,
        2.56880678-1.16445939j])

2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

In [149]:
arr13 = np.random.randint(1,20,(2,3))

In [148]:
arr14 = np.ones((3,2))

In [150]:
arr13

array([[13, 14,  6],
       [13, 17, 10]], dtype=int32)

In [151]:
arr14

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [155]:
np.dot(arr13,arr14)

array([[33., 33.],
       [40., 40.]])

In [153]:
arr13 @ arr14

array([[33., 33.],
       [40., 40.]])

### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).

In [158]:
arr15 = np.arange(1,10).reshape(3,3)

In [159]:
arr15

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [161]:
arr15 = arr15.reshape(1,9)

In [162]:
arr15

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [164]:
arr15 = arr15.reshape(9,1)

In [165]:
arr15

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

In [166]:
arr16 = np.random.randint(1,100,(5,5))

In [167]:
arr16

array([[73, 73, 79, 60,  2],
       [96, 12, 31,  3, 53],
       [65, 56, 94, 87, 52],
       [16, 23, 13, 63, 58],
       [62, 43, 39, 62, 81]], dtype=int32)

In [169]:
arr16 = arr16.flatten()

In [170]:
arr16

array([73, 73, 79, 60,  2, 96, 12, 31,  3, 53, 65, 56, 94, 87, 52, 16, 23,
       13, 63, 58, 62, 43, 39, 62, 81], dtype=int32)

In [171]:
arr16 = arr16.reshape(5,5)

In [172]:
arr16

array([[73, 73, 79, 60,  2],
       [96, 12, 31,  3, 53],
       [65, 56, 94, 87, 52],
       [16, 23, 13, 63, 58],
       [62, 43, 39, 62, 81]], dtype=int32)

### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.

In [173]:
arr17 = np.random.randint(1,20,(5,5))

In [174]:
arr17

array([[11,  3, 10,  8, 15],
       [ 7, 17, 19,  2, 16],
       [ 3,  8,  9, 11,  4],
       [15,  4,  4, 16, 14],
       [ 2, 15,  8, 13, 19]], dtype=int32)

In [195]:
arr17[[0 , -1 , 0 , -1] , [0 , 0 , -1 , -1]]

array([11,  2, 15, 19], dtype=int32)

2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

In [202]:
arr18 = np.random.randint(1,18,(4,4))

In [203]:
np.max(arr18)

np.int32(14)

In [204]:
arr18[arr18 > 10] = 10

In [205]:
arr18

array([[10,  2, 10,  5],
       [ 2,  6,  2,  1],
       [ 1,  5,  3,  5],
       [10,  8,  1, 10]], dtype=int32)

In [206]:
np.max(arr18)

np.int32(10)

### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.

In [213]:
data_type = [('name', 'U10'), ('age', 'i4'), ('weight', 'f4')]
arr19 = np.array([('Alice', 25, 55.5), ('Bob', 30, 85.3), ('Charlie', 20, 65.2)], dtype=data_type)

In [214]:
arr19

array([('Alice', 25, 55.5), ('Bob', 30, 85.3), ('Charlie', 20, 65.2)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f4')])

In [217]:
np.sort(arr19,order='age')

array([('Charlie', 20, 65.2), ('Alice', 25, 55.5), ('Bob', 30, 85.3)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f4')])

2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

In [230]:
# Create a structured array with fields 'x' and 'y'
data_type = [('x', 'i4'), ('y', 'i4')]
data = np.array([(1, 2), (3, 4), (5, 6)], dtype=data_type)
print("Original array:")
print(data)

# Compute the Euclidean distance between each pair of points
distances = np.sqrt((data['x'][:, np.newaxis] - data['x'])**2 + (data['y'][:, np.newaxis] - data['y'])**2)
print("Euclidean distances:")
print(distances)

Original array:
[(1, 2) (3, 4) (5, 6)]
Euclidean distances:
[[0.         2.82842712 5.65685425]
 [2.82842712 0.         2.82842712]
 [5.65685425 2.82842712 0.        ]]


In [219]:
a = np.array([1,2])

In [223]:
a

array([1, 2])

In [220]:
a.shape

(2,)

In [227]:
a = a[:,np.newaxis]

In [228]:
a

array([[1],
       [2]])

In [229]:
a.shape

(2, 1)

### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.

In [231]:
arr21 = np.random.randint(1,20,(4,4))

In [232]:
arr21

array([[19, 12, 17, 19],
       [ 7,  5,  5, 15],
       [10, 17, 10,  2],
       [ 1, 15,  2,  6]], dtype=int32)

In [233]:
import numpy.ma as ma

In [235]:
masked_arr21 = ma.masked_greater(arr21,10)

In [236]:
arr21

array([[19, 12, 17, 19],
       [ 7,  5,  5, 15],
       [10, 17, 10,  2],
       [ 1, 15,  2,  6]], dtype=int32)

In [237]:
masked_arr21

masked_array(
  data=[[--, --, --, --],
        [7, 5, 5, --],
        [10, --, 10, 2],
        [1, --, 2, 6]],
  mask=[[ True,  True,  True,  True],
        [False, False, False,  True],
        [False,  True, False, False],
        [False,  True, False, False]],
  fill_value=np.int64(999999),
  dtype=int32)

In [247]:
masked_arr21

masked_array(
  data=[[--, --, --, --],
        [7, 5, 5, --],
        [10, --, 10, 2],
        [1, --, 2, 6]],
  mask=[[ True,  True,  True,  True],
        [False, False, False,  True],
        [False,  True, False, False],
        [False,  True, False, False]],
  fill_value=np.int64(999999),
  dtype=int32)

In [252]:
masked_arr21.sum()

np.int64(48)

2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [271]:
arr22 = np.random.randint(1,20,(3,3))

In [272]:
masked_arr22 = ma.masked_array(arr22,mask=np.eye(3))

In [273]:
masked_arr22

masked_array(
  data=[[--, 17, 8],
        [19, --, 1],
        [2, 18, --]],
  mask=[[ True, False, False],
        [False,  True, False],
        [False, False,  True]],
  fill_value=np.int64(999999),
  dtype=int32)

In [278]:
masked_mean = masked_arr22.mean()

In [281]:
masked_mean

np.float64(10.833333333333334)

In [279]:
new_masked_array = masked_arr22.filled(masked_mean)

In [280]:
new_masked_array

array([[10, 17,  8],
       [19, 10,  1],
       [ 2, 18, 10]], dtype=int32)