In [1]:

# Numpy - Array Manipulation

In [2]:
import numpy as np

In [3]:
arr = np.random.randint(1,10,(3,4))

In [4]:
arr

array([[6, 4, 6, 6],
       [3, 8, 9, 6],
       [3, 9, 7, 2]], dtype=int32)

In [6]:
arr.reshape(2,-77878)

array([[6, 4, 6, 6, 3, 8],
       [9, 6, 3, 9, 7, 2]], dtype=int32)

In [7]:
arr.T

array([[6, 3, 3],
       [4, 8, 9],
       [6, 9, 7],
       [6, 6, 2]], dtype=int32)

In [8]:
arr.flatten() # will convert it to 1D array

array([6, 4, 6, 6, 3, 8, 9, 6, 3, 9, 7, 2], dtype=int32)

In [9]:
arr1 = np.array([1,2,3,3,4])

In [10]:
arr1.ndim

1

In [11]:
np.expand_dims(arr1,axis=1) # will convert it to 2D array

array([[1],
       [2],
       [3],
       [3],
       [4]])

In [12]:
np.expand_dims(arr1,axis=0) # will convert it to 2D array


array([[1, 2, 3, 3, 4]])

In [14]:
np.squeeze(arr)

array([[6, 4, 6, 6],
       [3, 8, 9, 6],
       [3, 9, 7, 2]], dtype=int32)

In [15]:
data = np.array([[1],[2],[3]])

In [16]:
data

array([[1],
       [2],
       [3]])

In [17]:
np.squeeze(data) # it squeezed to 1d array it will convert to 1d only if there is single element else not

array([1, 2, 3])

In [18]:
arr1

array([1, 2, 3, 3, 4])

In [19]:
np.repeat(arr1,3) # will repeat every element 3 times in the array

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4, 4])

In [20]:
np.roll(arr1,2) # will rotate every element 2 times

array([3, 4, 1, 2, 3])

In [21]:
np.diag(arr1) # will keep every element in daigonal

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4]])

In [22]:
#Numpy - Binary Operation

In [23]:
arr1 = np.random.randint(1,10,(3,4))
arr2 = np.random.randint(1,10,(3,4))


In [24]:
arr1 + arr2

array([[ 6,  9, 16, 14],
       [12, 14, 10,  3],
       [14, 13, 11,  9]], dtype=int32)

In [25]:
arr1

array([[1, 3, 7, 6],
       [4, 5, 4, 2],
       [9, 5, 8, 4]], dtype=int32)

In [26]:
arr2

array([[5, 6, 9, 8],
       [8, 9, 6, 1],
       [5, 8, 3, 5]], dtype=int32)

In [27]:
arr1 % arr2

array([[1, 3, 7, 6],
       [4, 5, 4, 0],
       [4, 5, 2, 4]], dtype=int32)

In [28]:
arr1 ** arr2

array([[       1,      729, 40353607,  1679616],
       [   65536,  1953125,     4096,        2],
       [   59049,   390625,      512,     1024]], dtype=int32)

In [29]:
arr1 & arr2 # binary and operation

array([[1, 2, 1, 0],
       [0, 1, 4, 0],
       [1, 0, 0, 4]], dtype=int32)

In [30]:
~ arr1 # negate operation 

array([[ -2,  -4,  -8,  -7],
       [ -5,  -6,  -5,  -3],
       [-10,  -6,  -9,  -5]], dtype=int32)

In [31]:
arr1 | arr2 # binary or operation

array([[ 5,  7, 15, 14],
       [12, 13,  6,  3],
       [13, 13, 11,  5]], dtype=int32)

In [32]:
arr1 > arr2

array([[False, False, False, False],
       [False, False, False,  True],
       [ True, False,  True, False]])

In [33]:
#Numpy - String Operation

In [41]:
arr = np.array(["abcd","xyz"])

In [42]:
arr

array(['abcd', 'xyz'], dtype='<U4')

In [43]:
np.char.upper(arr) # will convert every string element to upper case

array(['ABCD', 'XYZ'], dtype='<U4')

In [44]:
np.char.title(arr) # will keep first letter of every element in upper case

array(['Abcd', 'Xyz'], dtype='<U4')

In [45]:
np.char.capitalize(arr)

array(['Abcd', 'Xyz'], dtype='<U4')

In [46]:
#Numpy - Mathematical Operations

In [47]:
arr1

array([[1, 3, 7, 6],
       [4, 5, 4, 2],
       [9, 5, 8, 4]], dtype=int32)

In [48]:
np.sin(arr1) # sin

array([[ 0.84147098,  0.14112001,  0.6569866 , -0.2794155 ],
       [-0.7568025 , -0.95892427, -0.7568025 ,  0.90929743],
       [ 0.41211849, -0.95892427,  0.98935825, -0.7568025 ]])

In [49]:
np.cos(arr1) # cos

array([[ 0.54030231, -0.9899925 ,  0.75390225,  0.96017029],
       [-0.65364362,  0.28366219, -0.65364362, -0.41614684],
       [-0.91113026,  0.28366219, -0.14550003, -0.65364362]])

In [51]:
np.tan(arr1) # tan

array([[ 1.55740772, -0.14254654,  0.87144798, -0.29100619],
       [ 1.15782128, -3.38051501,  1.15782128, -2.18503986],
       [-0.45231566, -3.38051501, -6.79971146,  1.15782128]])

In [52]:
np.tanh(arr1) #tanh

array([[0.76159416, 0.99505475, 0.99999834, 0.99998771],
       [0.9993293 , 0.9999092 , 0.9993293 , 0.96402758],
       [0.99999997, 0.9999092 , 0.99999977, 0.9993293 ]])

In [53]:
np.log10(arr1) #log10

array([[0.        , 0.47712125, 0.84509804, 0.77815125],
       [0.60205999, 0.69897   , 0.60205999, 0.30103   ],
       [0.95424251, 0.69897   , 0.90308999, 0.60205999]])

In [54]:
np.power(arr1,3)

array([[  1,  27, 343, 216],
       [ 64, 125,  64,   8],
       [729, 125, 512,  64]], dtype=int32)

In [55]:
np.mean(arr1)

np.float64(4.833333333333333)

In [57]:
np.median(arr1)

np.float64(4.5)

In [58]:
np.std(arr1)

np.float64(2.266911751455907)

In [59]:
np.var(arr1)

np.float64(5.138888888888889)

In [60]:
np.min(arr1)

np.int32(1)

In [61]:
np.max(arr1)

np.int32(9)