In [2]:
import numpy as np

In [4]:
arr1 = np.array([7,8,4,5,6,1,25,2,4])

In [5]:
arr1

array([ 7,  8,  4,  5,  6,  1, 25,  2,  4])

In [6]:
np.sort(arr1) # sort arrays

array([ 1,  2,  4,  4,  5,  6,  7,  8, 25])

In [8]:
np.searchsorted(arr1,3) # will give location that where element 3 will go in arr1

np.int64(0)

In [10]:
arr1 = np.array([0,14,589,125,456,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0])

In [11]:
np.count_nonzero(arr1) # will give count of non zero elements

4

In [14]:
arr1

array([  0,  14, 589, 125, 456,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0])

In [13]:
np.where(arr1 > 6) # will give index that where are elements greater than 6 available

(array([1, 2, 3, 4]),)

In [15]:
np.extract(arr1>6,arr1) # will give extract values

array([ 14, 589, 125, 456])

In [16]:
#Numpy - Byte swapping

In [18]:
arr1

array([  0,  14, 589, 125, 456,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0])

In [19]:
arr1.byteswap() # convert to byte swapping

array([                   0,  1008806316530991104,  5548997690873872384,
        9007199254740992000, -4034943791147253760,                    0,
                          0,                    0,                    0,
                          0,                    0,                    0,
                          0,                    0,                    0,
                          0,                    0,                    0,
                          0,                    0])

In [20]:
#Numpy - Copies & Views

In [21]:
arr1

array([  0,  14, 589, 125, 456,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0])

In [22]:
a = np.copy(arr1) # deep copy

In [23]:
b = arr1.view() # shallow copy

In [24]:
b[0]

np.int64(0)

In [25]:
b[0] = 67

In [26]:
b

array([ 67,  14, 589, 125, 456,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0])

In [27]:
arr1

array([ 67,  14, 589, 125, 456,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0])

In [28]:
#Numpy - matrix library

In [29]:
import numpy.matlib as nm

In [30]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [31]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [32]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [33]:
#Numpy - linear algebra

In [34]:
arr1 = np.random.randint([[2,3],[4,5]])

In [35]:
arr2 = np.random.randint([[5,3],[2,5]])

In [36]:
arr1

array([[0, 2],
       [2, 2]], dtype=int32)

In [37]:
arr2

array([[1, 1],
       [1, 3]], dtype=int32)

In [38]:
np.dot(arr1,arr2) # dot product

array([[2, 6],
       [4, 8]], dtype=int32)

In [39]:
arr1@arr2

array([[2, 6],
       [4, 8]], dtype=int32)