In [1]:
pip install numpy

In [2]:
import numpy as np

In [3]:
l = [1,2,3,4]

In [4]:
ar = np.array(l) # method 1 create array

In [5]:
ar

array([1, 2, 3, 4])

In [6]:
type(ar)

numpy.ndarray

In [8]:
np.array([[1,2],[3,4]]) # method 1 create matrix

array([[1, 2],
       [3, 4]])

In [9]:
np.asarray(l) # method 2 create array

array([1, 2, 3, 4])

In [10]:
a = [2,3,4]

In [11]:
np.asanyarray(a) # method 3 create array

array([2, 3, 4])

In [12]:
np.matrix([1,2,3,4]) # method 2 create matrix

matrix([[1, 2, 3, 4]])

In [13]:
a = np.array(l)

In [14]:
c = a # shallow copy

In [15]:
c

array([1, 2, 3, 4])

In [16]:
a

array([1, 2, 3, 4])

In [17]:
a[0] = 100

In [18]:
a

array([100,   2,   3,   4])

In [19]:
c

array([100,   2,   3,   4])

In [20]:
d = np.copy(a) # copy in a new location i.e deep copy

In [21]:
d

array([100,   2,   3,   4])

In [22]:
a

array([100,   2,   3,   4])

In [23]:
a[1] = 400

In [24]:
a

array([100, 400,   3,   4])

In [25]:
d # no change in d it is deep copy

array([100,   2,   3,   4])

In [27]:
np.fromfunction(lambda i,j : i == j , (3,3)) # it will generate 3x3 data with help of lambda function. where i = row , j = column

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [28]:
np.fromfunction(lambda i,j : i * j , (3,3)) # it will generate 3x3 data with help of lambda function. where i = row , j = column

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [29]:
iterable = (i*i for i in range(5))

In [30]:
np.fromiter(iterable,float) # can also create array from iterable

array([ 0.,  1.,  4.,  9., 16.])

In [31]:
np.fromstring('234 234',sep=' ') # can also create array from string

array([234., 234.])

In [32]:
np.fromstring('234,234',sep=',') # can also create array from string

array([234., 234.])

In [33]:
# Numpy - Data Types.

In [34]:
l = [2,3,4,5,6]

In [35]:
ar = np.array(l)

In [36]:
ar

array([2, 3, 4, 5, 6])

In [37]:
ar.ndim # will show number of dimension of array

1

In [38]:
ar2 = np.array([[1,2,3,4],[2,3,4,5]])

In [39]:
ar2

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [40]:
ar2.ndim

2

In [41]:
ar.size # will tell how many elements are there in array

5

In [42]:
ar2.size

8

In [43]:
ar.shape # will give (row,column) if one dimensional then (column,)

(5,)

In [44]:
ar2.shape

(2, 4)

In [45]:
ar.dtype # will give data type

dtype('int64')

In [46]:
ar2.dtype

dtype('int64')

In [47]:
ar22 = np.array([(1.4,45,45),(23,45,66)]) # will change all to float types

In [48]:
ar22

array([[ 1.4, 45. , 45. ],
       [23. , 45. , 66. ]])

In [51]:
ar22.dtype

dtype('float64')

In [54]:
np.arange(2.5,5.6,0.3) # to generate array in range

array([2.5, 2.8, 3.1, 3.4, 3.7, 4. , 4.3, 4.6, 4.9, 5.2, 5.5])

In [55]:
list(np.arange(2.5,5.6,0.3)) # to generate array in range equivalent to range() but it cannot produce float values

[np.float64(2.5),
 np.float64(2.8),
 np.float64(3.0999999999999996),
 np.float64(3.3999999999999995),
 np.float64(3.6999999999999993),
 np.float64(3.999999999999999),
 np.float64(4.299999999999999),
 np.float64(4.599999999999999),
 np.float64(4.899999999999999),
 np.float64(5.199999999999998),
 np.float64(5.499999999999998)]

In [56]:
np.linspace(1,5,10) # will produce 10 elements between 1 to 5

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [57]:
np.zeros(5) # will produce array with 5 zero elements

array([0., 0., 0., 0., 0.])

In [58]:
np.zeros((3,4)) # will produce array with 3 rows and 4 columns

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [59]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [60]:
np.ones(4) # same as np.zeros()

array([1., 1., 1., 1.])

In [62]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [64]:
one = np.ones((3,4,2)) # same as np.ones

In [65]:
one

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [66]:
one + 5

array([[[6., 6.],
        [6., 6.],
        [6., 6.],
        [6., 6.]],

       [[6., 6.],
        [6., 6.],
        [6., 6.],
        [6., 6.]],

       [[6., 6.],
        [6., 6.],
        [6., 6.],
        [6., 6.]]])

In [67]:
one * 4

array([[[4., 4.],
        [4., 4.],
        [4., 4.],
        [4., 4.]],

       [[4., 4.],
        [4., 4.],
        [4., 4.],
        [4., 4.]],

       [[4., 4.],
        [4., 4.],
        [4., 4.],
        [4., 4.]]])

In [68]:
np.empty(5) # create empty array

array([0., 0., 0., 0., 0.])

In [69]:
np.empty((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [70]:
np.empty((3,5))

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 6.81019663e-310]])

In [72]:
np.eye(4) # will create identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [74]:
np.logspace(2,5,10,base = 2) # will create log of 10 elements between 2 and 5

array([ 4.        ,  5.0396842 ,  6.34960421,  8.        , 10.0793684 ,
       12.69920842, 16.        , 20.1587368 , 25.39841683, 32.        ])

In [75]:
# random function

In [76]:
np.random.randn(3,4) # will produce random data in 3x4 matrix whose mean is 0 and std is 1

array([[-0.23676589,  0.40473789,  0.49259559, -0.85742196],
       [ 0.45825309, -0.02529436, -0.99883907,  0.92411477],
       [-0.077138  , -0.36674158, -0.45050632, -0.30624574]])

In [77]:
arr = np.random.randn(3,4)

In [78]:
import pandas as pd

In [79]:
pd.DataFrame(arr)

0         1         2         3
0 -1.481307 -0.417136 -2.448161 -0.842412
1 -0.440692 -1.003538  0.349801  1.672385
2 -0.150011 -0.410313 -1.570130  1.849418

In [80]:
np.random.rand(3,4) # will produce random data in 3x4 matrix

array([[0.26911637, 0.4919391 , 0.69847827, 0.34555438],
       [0.88255875, 0.11532748, 0.3815313 , 0.82255061],
       [0.53076139, 0.87999824, 0.91784624, 0.393553  ]])

In [81]:
np.random.randint(1,110,(3,4)) # will produce random integer data between 1 and 110

array([[40, 85, 54, 69],
       [17, 14, 19, 91],
       [15, 71, 88, 52]], dtype=int32)

In [83]:
pd.DataFrame(np.random.randint(1,110,(300,400))).to_csv('random_int_data.csv')

In [84]:
arr = np.random.rand(3,4)

In [85]:
arr

array([[0.9583129 , 0.06836304, 0.78447355, 0.01032536],
       [0.99320374, 0.04429603, 0.32704186, 0.35240246],
       [0.21735905, 0.3935352 , 0.92753397, 0.41575884]])

In [86]:
arr.reshape(6,2) # will reshape data and its multiplications should be same as number of elements

array([[0.9583129 , 0.06836304],
       [0.78447355, 0.01032536],
       [0.99320374, 0.04429603],
       [0.32704186, 0.35240246],
       [0.21735905, 0.3935352 ],
       [0.92753397, 0.41575884]])

In [88]:
arr1 = arr.reshape(6,-1233) # will reshape data and its multiplications , if any negative number is given then it will automatically reshape

In [89]:
arr1

array([[0.9583129 , 0.06836304],
       [0.78447355, 0.01032536],
       [0.99320374, 0.04429603],
       [0.32704186, 0.35240246],
       [0.21735905, 0.3935352 ],
       [0.92753397, 0.41575884]])

In [90]:
arr1[1][1]

np.float64(0.010325363405434329)

In [94]:
arr1[2:5,1] # to access data slicing

array([0.04429603, 0.35240246, 0.3935352 ])

In [95]:
arr = np.random.randint(1,100,(5,5))

In [96]:
arr

array([[44, 53, 11, 79,  9],
       [ 8, 29, 22, 92, 39],
       [62, 53,  6, 42,  5],
       [30, 15, 75, 26, 52],
       [30, 77, 53, 30, 63]], dtype=int32)

In [97]:
arr > 50

array([[False,  True, False,  True, False],
       [False, False, False,  True, False],
       [ True,  True, False, False, False],
       [False, False,  True, False,  True],
       [False,  True,  True, False,  True]])

In [98]:
arr[arr > 50] # conditional formatting like pandas

array([53, 79, 92, 62, 53, 75, 52, 77, 53, 63], dtype=int32)

In [100]:
arr[2:4,[1,2]] # to access data

array([[53,  6],
       [15, 75]], dtype=int32)

In [101]:
arr[0][0] = 5000

In [102]:
arr

array([[5000,   53,   11,   79,    9],
       [   8,   29,   22,   92,   39],
       [  62,   53,    6,   42,    5],
       [  30,   15,   75,   26,   52],
       [  30,   77,   53,   30,   63]], dtype=int32)

In [103]:
arr1 = np.random.randint(1,3,(3,3))
arr2 = np.random.randint(1,3,(3,3))

In [104]:
arr1

array([[1, 1, 1],
       [2, 2, 2],
       [2, 1, 1]], dtype=int32)

In [105]:
arr2

array([[1, 2, 1],
       [2, 2, 1],
       [1, 1, 2]], dtype=int32)

In [106]:
arr1 + arr2 # adding 2 arrays

array([[2, 3, 2],
       [4, 4, 3],
       [3, 2, 3]], dtype=int32)

In [107]:
arr1 - arr2 # subtracting 2 arrays

array([[ 0, -1,  0],
       [ 0,  0,  1],
       [ 1,  0, -1]], dtype=int32)

In [108]:
arr1 / arr2 # dividing 2 arrays

array([[1. , 0.5, 1. ],
       [1. , 1. , 2. ],
       [2. , 1. , 0.5]])

In [109]:
arr1 * arr2 # not matrix multiplication

array([[1, 2, 1],
       [4, 4, 2],
       [2, 1, 2]], dtype=int32)

In [110]:
arr1 @ arr2 # this gives matrix multiplication

array([[ 4,  5,  4],
       [ 8, 10,  8],
       [ 5,  7,  5]], dtype=int32)

In [111]:
arr1 / 0 # this will give infinity

C:\Users\DELL\AppData\Local\Temp\ipykernel_10944\4215953818.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1 / 0 # this will give infinity


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [112]:
arr1 ** 2

array([[1, 1, 1],
       [4, 4, 4],
       [4, 1, 1]], dtype=int32)

In [113]:
# Numpy - Broadcasting

In [114]:
arr = np.zeros((4,4))

In [115]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [116]:
row = np.array([1,2,3,4])

In [117]:
arr + row # it is adding in every row

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [118]:
row.shape

(4,)

In [120]:
row.T # to transpose

array([1, 2, 3, 4])

In [121]:
col = np.array([[1,2,3,4]])

In [122]:
col

array([[1, 2, 3, 4]])

In [123]:
col.shape

(1, 4)

In [126]:
col = col.T # to transponse matrix

In [127]:
col

array([[1],
       [2],
       [3],
       [4]])

In [128]:
arr + col # now it is adding column wise 

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [129]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [131]:
arr1 = np.random.randint(1,4,(3,4))

In [132]:
arr1

array([[2, 3, 3, 1],
       [2, 1, 1, 1],
       [3, 3, 1, 1]], dtype=int32)

In [133]:
np.sqrt(arr1) # square root

array([[1.41421356, 1.73205081, 1.73205081, 1.        ],
       [1.41421356, 1.        , 1.        , 1.        ],
       [1.73205081, 1.73205081, 1.        , 1.        ]])

In [134]:
np.exp(arr1) # exponent 

array([[ 7.3890561 , 20.08553692, 20.08553692,  2.71828183],
       [ 7.3890561 ,  2.71828183,  2.71828183,  2.71828183],
       [20.08553692, 20.08553692,  2.71828183,  2.71828183]])

In [135]:
np.log10(arr1) # log 10

array([[0.30103   , 0.47712125, 0.47712125, 0.        ],
       [0.30103   , 0.        , 0.        , 0.        ],
       [0.47712125, 0.47712125, 0.        , 0.        ]])